from .CharacterLevelWordEmbedding import CharacterLevelWordEmbedding
from .CharacterLevelWordEmbedding import CharacterLevelWordSparseEncoding
from .CharacterLevelWordEmbedding import PositionalCharacterLevelWordEmbedding
from .CharacterLevelWordEmbedding import PositionalCharacterLevelWordSparseEncoding
from .CharacterLevelWordEmbedding import RNNCharacterLevelWordEmbedding
from .CharacterLevelWordEmbedding import GRUCharacterLevelWordEmbedding
from .CharacterLevelWordEmbedding import LSTMCharacterLevelWordEmbedding

from .NgramLevelWordEmbedding import NgramLevelWordEmbedding
from .NgramLevelWordEmbedding import NgramLevelWordSparseEncoding

from .MultiSpacesWordEmbedding import NonlinearTransformation
from .MultiSpacesWordEmbedding import PassThroughAuxiliarySpaceWordEmbedding
from .MultiSpacesWordEmbedding import SummationAuxiliarySpaceWordEmbedding
from .MultiSpacesWordEmbedding import AveragingAuxiliarySpaceWordEmbedding